### ISSUE TITLE
Report device information

### ISSUE THREAD

**Issue by deanmcpherson** [lwansbrough/react-native-google-analytics#11]
Hey @lwansbrough, thanks for this library it was really easy to get up and running. I managed to get views / events flowing into GA really easily. 

Looking at what's currently being reported, ga has no idea about device metrics (model, screen size, OS version, etc) which might be useful.

I'm playing with reporting viewport sizing as well in Analytics.send but was wondering if you had any idea of how to easily report the rest (model, OS version)?

**Comment by lwansbrough** [comment]
@deanmcpherson Sorry for the delayed response. Check out this module: https://github.com/GertjanReynaert/react-native-device

**Comment by deanmcpherson** [comment]
Thanks @lwansbrough
