### ISSUE TITLE
Doesn't work in React Native 0.14.0-rc?

### ISSUE THREAD

**Issue by gudmundurmar** [lwansbrough/react-native-google-analytics#14]
I haven't been able to get the package to work in 0.14.0-rc (trouble with RCTAdSupport)
Is this just me or is it a problem for others too?

p.s. it's currently working for me in 0.13.0

**Comment by lwansbrough** [comment]
Hmm. Obviously I'm not supporting release candidates - but please let me know if this issue persists when the final version comes out. For now, can you explain more in detail what issue is arising with the RCTAdSupport module?

**Comment by petrvojta** [comment]
Hi, the problem persists also in the final version 0.14.0. A Build process in XCode ends with: `Command /bin/sh failed with exit code 1`, and there is an error: `uncaught error Error: UnableToResolveError: Unable to resolve module AdSupportIOS from ./node_modules/react-native-google-analytics/lib/Tracking.js: Invalid directory /Users/node_modules/AdSupportIOS` ... please check it out. thx.
