### ISSUE TITLE
Android documentation

### ISSUE THREAD

**Issue by olitomas** [lwansbrough/react-native-google-analytics#16]
Update the readme to include Android setup ( if it is supported that is ? )

**Comment by ghost** [comment]
+1

**Comment by lwansbrough** [comment]
Just pushed version `0.1.0` to npm, which addresses this issue by removing the client ID generation and delegating the responsibility to the app developer. I'd recommend using https://github.com/rebeccahughes/react-native-device-info to generate a UUID.
