### ISSUE TITLE
Is it a good idea to use AdSupportIOS as client id for GA?

### ISSUE THREAD

**Issue by cbrevik** [lwansbrough/react-native-google-analytics#18]
I've been developing an app that is going to use Google Analytics, and I've forked this module in mind to also implement Android support. While doing that though I came across the following SO post; 

http://stackoverflow.com/questions/21489097/my-app-was-just-rejected-for-using-the-ad-support-framework-which-library-is-re

Specifically the following;

> We found your app uses the iOS Advertising Identifier but does not include ad functionality. This does not comply with the terms of the iOS Developer Program License Agreement, as required by the App Store Review Guidelines.
> 
> class: ASIdentifierManager
> selector: advertisingIdentifier
> framework: AdSupport.framework

So my question would be, is it a good idea to use [AdSupportIOS](https://github.com/facebook/react-native/blob/master/Libraries/AdSupport/RCTAdSupport.m) as to retrieve a "client id" in Tracking.js when it might get your app rejected from the App Store if you're not serving ads (just using analytics)?

**Comment by lwansbrough** [comment]
Good question, and I'm unsure of the answer. You could generate a UUID and save it locally, or in cloud storage. I'd consider removing it from this lib if there's a better replacement.

**Comment by lwansbrough** [comment]
`[[[UIDevice currentDevice] identifierForVendor] UUIDString]` is what this library should be using by the looks of it. IMO this library should not require a static lib to work - I'll see about getting that ID implemented in React Native core.

**Comment by cbrevik** [comment]
Looks like this will give you that; https://github.com/rebeccahughes/react-native-device-info (while also cross-platform). I haven't tested it out though.

**Comment by lwansbrough** [comment]
@cbrevik Yeah that should be merged into core IMO. Really useful stuff there.
