### ISSUE TITLE
Not working with react-native 0.7.0-rc.2

### ISSUE THREAD

**Issue by PhilippKrone** [lwansbrough/react-native-google-analytics#2]
Hi,

the fetch() statement creates an error in RCTNetworking.m (see https://github.com/facebook/react-native/issues/1780).

Regards
Philipp

**Comment by PhilippKrone** [comment]
@lwansbrough Please see https://github.com/facebook/react-native/issues/1780

**Comment by jacob-israel-turner** [comment]
Should this issue be closed now?

**Comment by dorthwein** [comment]
Running into the same issue - I previously got it working on another app but no luck now....

**Comment by lwansbrough** [comment]
@dorthwein Check out the thread linked above. It's probably not going to be fixed for iOS 7 unfortunately.

**Comment by dorthwein** [comment]
I read through the thread but the issue is persisting on iOS 9 simulator.

**Comment by lwansbrough** [comment]
@dorthwein Interesting, I'll look into it when I get a chance. If you discover the issue and have a fix, feel free to submit a PR. Thanks for resurfacing this issue.

**Comment by lwansbrough** [comment]
Thanks @dorthwein for resolving this issue with an elegant fix.

**Comment by nicholasalanbrown** [comment]
This might be related, I get this error in Xcode when following a simple parallel to your setup instructions:

```
[tid:com.facebook.React.RCTNetworkingQueue][RCTNetworking.m:320] Received data was not a string, or was not a recognised encoding.
```

I get the same in the Chrome console. I also see no data tracked in Google Analytics. Here's my code:

```
import React from 'react-native';
import globalStyles from '../styles/styles';
import Colors from '../styles/colors';
import Config from '../config';
let {
  AppRegistry,
  View,
  Text,
  Image,
  TouchableOpacity,
  StyleSheet,
  Animated,
  Easing,
  Dimensions,
  StatusBarIOS,
  ScrollView,
} = React;

var {
  Analytics,
  Tracking: GATracking,
  Hits: GAHits,
  Experiment: GAExperiment
} = require('react-native-google-analytics');

let {
  width: deviceWidth,
  height: deviceHeight
} = Dimensions.get('window');

var ga = this.ga = null;

class Welcome extends React.Component{
  componentWillMount() {
    GATracking.getClientId(function(err, clientId) {
      ga = new Analytics('UA-47880XXX-X', clientId);
      var screenView = new GAHits.ScreenView('GA Test', '1', 'org.reactjs.native.example.test');
      ga.send(screenView);
    });
  }
```

**Comment by ilanasufrin** [comment]
@nicholasalanbrown I'm having the same problem as you. Did you ever get a fix?

**Comment by nicholasalanbrown** [comment]
@lwansbrough still haven't been able to get it to work, though @lwansbrough did offer to take a look after I posted to the Facebook React Native Community.

**Comment by nicholasalanbrown** [comment]
Just tried again but still consistently get this error:

![image](https://cloud.githubusercontent.com/assets/3259022/11491545/dd16ce04-97b0-11e5-8ae0-bf76732e772f.png)

..and still no data showing in GA

**Comment by tgoldenberg** [comment]
@lwansbrough, any update on this issue? I tried the above code after following the README and got the same error. Does this have anything to do with the version of RN? I am using `"react-native": "^0.14.2",`

**Comment by nicholasalanbrown** [comment]
I tried downgrading to `0.13.0` and still got the same error FWIW.

**Comment by lwansbrough** [comment]
https://github.com/facebook/react-native/issues/1780 It was being tracked there. Are you guys using iOS 7?

**Comment by Sexycrets** [comment]
Had the same issue. Switching iOS from 7.0 to 8.1 solved it. I receive the events on GA. 

The "Received data was not a string, or was not a recognised encoding." warning is still present.

**Comment by lwansbrough** [comment]
@Sexycrets Thanks for the update

**Comment by adamloving** [comment]
Still seeing this on iOS 9.3. Tracked the error message down to here: https://github.com/facebook/react-native/blob/master/Libraries/Network/RCTNetworking.m#L330 Looks like the response from ga.send() contains data, but cannot be decoded.

**Comment by lwansbrough** [comment]
@adamloving Yeah, it's been an ongoing issue. You get a warning but the analytics are sent fine. The response is irrelevant. It's a React Native bug - image data isn't supported over XHR.
