### ISSUE TITLE
Is setting GA custom dimension supported?

### ISSUE THREAD

**Issue by Sexycrets** [lwansbrough/react-native-google-analytics#29]
I need to send a GA Custom Dimension from my app, I could not find an example in the current documentation.

Is this a supported feature?

**Comment by kevinhylant** [comment]
+1 (read through the source code & it doesn't seem to currently support it). Would love this feature as well

**Comment by lwansbrough** [comment]
Fixed by https://github.com/lwansbrough/react-native-google-analytics/pull/30
