### ISSUE TITLE
Latest update broke initialization

### ISSUE THREAD

**Issue by adeelraza** [lwansbrough/react-native-google-analytics#31]
It now throws an error on:

```
ga = new Analytics(...)
```

**Comment by ilanasufrin** [comment]
👍 , the initialization error is also occurring on my project and I had to downgrade

**Comment by anativ** [comment]
+1

**Comment by lwansbrough** [comment]
Sup, sorry!! Should have noticed this sooner too. Please upgrade to `1.3.2` -- the issue should be resolved there.
