### ISSUE TITLE
Clarify AdSupport dependency in README

### ISSUE THREAD

**Issue by jacob-israel-turner** [lwansbrough/react-native-google-analytics#5]
It took me a little bit and a discussion on slack to realize thatI needed to manually add AdSupport to the native modules in order for this library to work.  It should be specified in the README.  I'm willing to write something up and make a PR.

**Comment by lwansbrough** [comment]
Yeah sorry this didn't used to be the case. I'd appreciate the PR as I'm not actually familiar with the steps to re-add AdSupport (though I can probably make an educated guess as to how it's done.)

**Comment by jacob-israel-turner** [comment]
:+1: Can do!
