### ISSUE TITLE
on app submission its asking for reason to use IDFA

### ISSUE THREAD

**Issue by jawadrehman** [lwansbrough/react-native-google-analytics#8]

**Comment by lwansbrough** [comment]
https://github.com/lwansbrough/react-native-google-analytics/blob/master/lib/Tracking.js#L7

For device tracking.

**Comment by scottgrubhub** [comment]
When trying to submit my App, the only three options allowed are:

(1) Serve advertisements within the app
(2) Attribute this app installation to a previously served advertisement
(3) Attribute an action taken within this app to a previously served advertisement

Which one of these options do you think should be checked?

**Comment by lwansbrough** [comment]
I guess 3, but this is an interesting development. Maybe there's a better device ID we can use.

**Comment by scottgrubhub** [comment]
I ended up taking out the dependency on AdSupport and using the [identifierForVendor](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIDevice_Class/#//apple_ref/occ/instp/UIDevice/identifierForVendor) which I believe works fine for the purpose of tracking a device on google analytics.

**Comment by MossP** [comment]
@scottgrubhub Do you have updated code for this alteration? I've just come across this issue now.
